### ISSUE TITLE
Copying assets to output

### ISSUE THREAD

**Issue by Falven** [AlexPshul/nxazure#10]
@AlexPshul does this executor support copying assets to output?
```
"targets": {
    "build": {
      "executor": "@nxazure/func:build",
      "options": {
        "assets": [
          "libs/api/data-access/src/lib/schemas/schema.graphqls"
        ]
      }
    },
}
```

**Comment by AlexPshul** [comment]
No, this is not supported but this is a great idea!
I will add it to my todo list.

**Comment by AlexPshul** [comment]
@Falven 
Just realized that I never actually tackled this issue.
Is it something that you found a workaround for?

**Comment by AlexPshul** [comment]
I'm closing the issue for now but I'm open to future discussions if this feature will still be needed
