### ISSUE TITLE
Can't find library imports

### ISSUE THREAD

**Issue by Falven** [AlexPshul/nxazure#11]
I am unable to load NX library modules from the function apps. It looks like typescript is not resolving the paths on transpilation:

myfunc/index.ts
```ts
import { test } from '@fldoe/admin-api/data-access';
```

dist/myfunc/index.js
```js
const data_access_1 = require("@fldoe/admin-api/data-access");
```

```shell
nx start admin-api

> nx run admin-api:start

Compiling TypeScript files for project "admin-api"...
Done compiling TypeScript files for project "admin-api".
Azure Functions Core Tools
Core Tools Version:       4.0.4915 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.14.0.19631
Functions:
        graphql: [GET,POST,OPTIONS] http://localhost:5001/{*segments}
For detailed output, run func with --verbose flag.
[2023-04-20T20:49:41.357Z] Worker process started and initialized.
[2023-04-20T20:49:41.654Z] Worker was unable to load function graphql: 'Cannot find module '@fldoe/admin-api/data-access'
Require stack:
- C:\source\repos\fldoe\fldoe\apps\admin-api\dist\apps\admin-api\graphql\index.js
- C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js
- C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\nodejsWorker.js'
[2023-04-20T20:49:41.665Z] Worker failed to load function: 'graphql' with function id: '57d6f68e-c742-4a10-ad59-b16351a8703a'.
[2023-04-20T20:49:41.666Z] Result: Failure
Exception: Worker was unable to load function graphql: 'Cannot find module '@fldoe/admin-api/data-access'
Require stack:
- C:\source\repos\fldoe\fldoe\apps\admin-api\dist\apps\admin-api\graphql\index.js
- C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js
- C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\nodejsWorker.js'
Stack: Error: Worker was unable to load function graphql: 'Cannot find module '@fldoe/admin-api/data-access'
Require stack:
- C:\source\repos\fldoe\fldoe\apps\admin-api\dist\apps\admin-api\graphql\index.js
- C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js
- C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\nodejsWorker.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at Object.apply (C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:41468)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\source\repos\fldoe\fldoe\apps\admin-api\dist\apps\admin-api\graphql\index.js:5:23)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
```
I also noticed there's some `_registerPaths.ts` code that gets generated, but never referenced in the dist files. Did I have to import this in my index.ts? If so, why?

@AlexPshul I've been stumped on this for a day. Any ideas why?

**Comment by Falven** [comment]
Oh yay. Importing it manually before my other imports seemed to resolve the issue:

```ts
import '../_registerPaths';
import { test } from '@fldoe/admin-api/data-access';
```

I would still be interested in discussing why this is needed, maybe we can document it in the readme as well and/or find a way to not need this bit.

**Comment by AlexPshul** [comment]
Hi @Falven,
Indeed, `import '../_registerPaths';` should be imported first. 
That's the reason that the generator creates it with the comment `// Import before any other lib imports`.
**BUT**, I agree, this should be highlighted in bold in the README.

The reason for that is because the way function apps are executed.
There is no way to modules before running your code. If you want to support the tsconfig paths, you **have** to use the `tsconfig-paths` lib and call the `register` function on your paths.

The workaround is to import a file that does the logic for you. That's why you have the dependency for `tsconfig-paths` in the package.json.


**With all that being said**, you should **not** update the `tsconfig.build.json` file.
The correct path (../..) is being injected for you in the build process. 
After running a build on your app, did the `tsconfig.build.json` got updated?
TBH, I'm not even sure why it worked for you the way you did.

Can you try again on a clean environment but leave the `import '../_registerPaths'` as the top most import?

**Comment by Falven** [comment]
> Hi @Falven, Indeed, `import '../_registerPaths';` should be imported first. That's the reason that the generator creates it with the comment `// Import before any other lib imports`. **BUT**, I agree, this should be highlighted in bold in the README.
> 
> The reason for that is because the way function apps are executed. There is no way to modules before running your code. If you want to support the tsconfig paths, you **have** to use the `tsconfig-paths` lib and call the `register` function on your paths.
> 
> The workaround is to import a file that does the logic for you. That's why you have the dependency for `tsconfig-paths` in the package.json.
> 
> **With all that being said**, you should **not** update the `tsconfig.build.json` file. The correct path (../..) is being injected for you in the build process. After running a build on your app, did the `tsconfig.build.json` got updated? TBH, I'm not even sure why it worked for you the way you did.
> 
> Can you try again on a clean environment but leave the `import '../_registerPaths'` as the top most import?

Yeah when the build system adds

```
"baseUrl": "."
```
Even if I:
```ts
import '../_registerPaths';
import { test } from '@fldoe/admin-api/data-access';
```
I get those errors that I fixed in the PR I sent.
However, if I use my fork such that the build system doesn't override the `baseUrl`, and manually set
```
"baseUrl": "..\.."
```
It builds and runs.

**Comment by AlexPshul** [comment]
Hmmm that's really odd. You shouldn't get any errors with `baseUrl: "."`.
I think I'm missing a use case or something. Do you care sharing with me a repo where I can also have a look?

Regarding the version, I'm working on it.
I have some failing tests. Once I fix it, the version will be out.

**Comment by Falven** [comment]
> Hmmm that's really odd. You shouldn't get any errors with `baseUrl: "."`. I think I'm missing a use case or something. Do you care sharing with me a repo where I can also have a look?
> 
> Regarding the version, I'm working on it. I have some failing tests. Once I fix it, the version will be out.

Sorry, I am desperately trying to deliver a project.
[Here's that sample.](https://github.com/Falven/nxazure-test)
Although it works now with the latest `1.0.11` release :)
