### ISSUE TITLE
Missing node_modules after publish

### ISSUE THREAD

**Issue by adenler01** [AlexPshul/nxazure#12]
Hi Alex -

Thanks for taking the time to create this package, it's much appreciated.

Forgive me if this is a dumb question - but should the publish command be publishing the node_modules folder contents necessary to run the function app?  I've downloaded the zip file that is pushed to azure storage by "nx publish project appname" and all of the compiled code is there, but no node_modules folder - so naturally my functions aren't running.

Thanks for the help in understanding this process.

Andy

**Comment by AlexPshul** [comment]
Hi @adenler01 ,
Thanks for reaching out.

This is odd, actually. The node_modules **are** being published.
I thought maybe I broke something so I retested it and all is working well for me.
Do you have a repo you can share with me to try it out and see if I can reproduce it?

**Comment by AlexPshul** [comment]
@adenler01,
Any update from your side?
Is it still failing?

**Comment by adenler01** [comment]
Hi Alex - thanks for the follow up.  It is now working, and honestly I can't tell you for sure why.  It APPEARS to be related to the fact that my repo was configured to use yarn workspaces as well as NX.  After removing the workspaces configuration it is now working correctly.

Thanks for the time - and thanks for creating this tool.

Andy

**Comment by AlexPshul** [comment]
Great!
I'm glad it's working and that you've found it useful.
