### ISSUE TITLE
Question: Does this work generically with mono-repos? Or strictly NX at this stage?

### ISSUE THREAD

**Issue by joelybahh** [AlexPshul/nxazure#16]
I'm working in turbo-repo. My solution has been to write a script that overrides the path on the `.json` files so I can use the deployment extension, but if this can be configured to work in turborepo that would be amazing.

**Comment by AlexPshul** [comment]
Hi @joelybahh ,
Unfortunately, I'm less familiar with turbo-repo and how it works.
Internally, in the executors, I'm using specific NX tools, so I don't know if this will work on other tools and monorepo frameworks.

**Comment by joelybahh** [comment]
@AlexPshul Thanks for the prompt reply! 

I might do some digging into the source code in any case, although it's NX specific, I might be able to extract out the Azure parts and try to apply the same concepts to Turborepo, thanks again!
