### ISSUE TITLE
ES Module support?

### ISSUE THREAD

**Issue by penleychan** [AlexPshul/nxazure#18]
Hello,

I am having difficulty setting up function app as modules is this something that can be configured to support it?

I've modified the tsconfig.json and tsconfig.build.json to have:

```
"module": "ES2022",
"target": "ES2022",
"moduleResolution": "node",
```

and included `type: "module"` in package.json

When I run it this is the error I get:
` Worker was unable to load function my-new-func: 'require is not defined in ES module scope, you can use import instead`

Regards

**Comment by AlexPshul** [comment]
Sorry for being quiet @penleychan, I was kind of busy lately.

Out of curiosity, why do you need ES Module support?

**Comment by penleychan** [comment]
No problem, majority of our library were written in ES Module. I was kinda able to get it working with modifying your nxazure/func project with combination of https://github.com/LeDDGroup/typescript-transform-paths and ts-patch Only caveat is that I need to provide the custom `@transform-path` for `typescript-transform-paths` plugin to output correct path. Bit unintuitive but works for now. Hopefully better solution in the future.

**Comment by AlexPshul** [comment]
Nice! Thanks for sharing!
If you ever get the time and the will, a PR with that solution would be very welcome!

**Comment by AlexPshul** [comment]
If and when you get the time @penleychan , feel free to reopen the issue to discuss this again.
