### ISSUE TITLE
Include @nx/devkit as a dependency

### ISSUE THREAD

**Issue by isaacplmann** [AlexPshul/nxazure#24]
This plugin doesn't have an Nx version listed in the [Nx Plugin Registry](https://nx.dev/extending-nx/registry) because the plugin doesn't include `@nx/devkit` as a dependency.  Could you please release a version that fixes that?

Thanks,
Isaac (Nx Team)

**Comment by AlexPshul** [comment]
Thanks for letting me know @isaacplmann,
I'll make sure it include it.

**Comment by AlexPshul** [comment]
@isaacplmann,
`@nx/devkit` was added as a dependency.
Let me know if something else is needed from my side.
