### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by tomflenner** [AlexPshul/nxazure#25]
Hi !

I have an error while building my azure function app :
![image](https://github.com/AlexPshul/nxazure/assets/59377281/60022301-8cfc-4ccd-8bc3-be5db604c3e4)

I am currently using :
- node v20.5.1
![image](https://github.com/AlexPshul/nxazure/assets/59377281/2edb7b0f-f882-4a36-9966-a8bddf7a0805)
- @types/node v18.7.1
![image](https://github.com/AlexPshul/nxazure/assets/59377281/e6d14159-d58f-456b-8fcc-e5de388e37d6)
- typescript v5.1.6
![image](https://github.com/AlexPshul/nxazure/assets/59377281/2e1b5ec2-204e-4913-934c-d6acd2d3a40d)
- nx v16.6
![image](https://github.com/AlexPshul/nxazure/assets/59377281/eba814ec-ebaa-4fe8-a80d-04c4d301cac8)

Maybe you have solution ?

Thank you !
Tom.

**Comment by AlexPshul** [comment]
Hi Tom,
Thanks for checking out the package. 😃 

As far as I remember, you cannot use node v20 with Azure Functions.
If I recall correctly, if you are using the V3 programming model, you must have node v16 installed and you can upgrade to node v18 if you are using V4 programming model (supported as an additional flag in the package).

Try downgrading to node v18 and run the package with V4 flag.
Let me know if it works.

**Comment by tomflenner** [comment]
Hi Alex,
Thank you for the fast answer 😁.

I tried with node version : 16.20.1 and 18.17.1 with Azure Function V3 programming model. I still issue the same error as above. 😢

For the moment I dont want to use V4 since it's still in preview.

Do you have another ideas ?

Thank you.

**Comment by tomflenner** [comment]
Ok, after using "npm-upgrade" to ensure that typescript and @ypes:Node are at latest versions build works ! 🎉.

Do you know If your executor support multiple function endpoints in same project (one index.js per endpoint) ?

**Comment by AlexPshul** [comment]
> Ok, after using "npm-upgrade" to ensure that typescript and @ypes:Node are at latest versions build works ! 🎉.

I'm glad it worked for you! Sorry, I forgot about the types thing that might go sideways.

> Do you know If your executor support multiple function endpoints in same project (one index.js per endpoint) ?

If I understand your question correctly - yes!
For a single app, just like a regular function app project, this will run all of your endpoints.
If you have multiple apps in your NX workspace, simply run all the targets together.
Try using `nx run-many --target=start --all --parallel=X`. Replace `X` with the number of projects you have and/or want to run in parallel.

**Comment by AlexPshul** [comment]
I'm closing this, but if you have any more questions, feel free to ask again.
