### ISSUE TITLE
`init` generator looking for `@azure/functions` in dependencies

### ISSUE THREAD

**Issue by wgd3** [AlexPshul/nxazure#29]
# Summary

When trying to initialize a new app, I got the following error:

```shell
> npx nx generate @nxazure/func:init my-new-app

TypeError: Cannot read properties of undefined (reading '@azure/functions')
    at createProjectPackageJson (/Users/wadani/code/github.com/azure-test/node_modules/@nxazure/func/src/generators/init/generator.js:105:65)
    at /Users/wadani/code/github.com/azure-test/node_modules/@nxazure/func/src/generators/init/generator.js:195:13
    at Generator.next (<anonymous>)
    at /Users/wadani/code/github.com/azure-test/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/wadani/code/github.com/azure-test/node_modules/tslib/tslib.js:165:16)
    at default_1 (/Users/wadani/code/github.com/azure-test/node_modules/@nxazure/func/src/generators/init/generator.js:177:20)
    at /Users/wadani/code/github.com/azure-test/node_modules/nx/src/command-line/generate/generate.js:241:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleErrors (/Users/wadani/code/github.com/azure-test/node_modules/nx/src/utils/params.js:9:16)

 >  NX   Cannot read properties of undefined (reading '@azure/functions')
```

I dove into the generator source code and saw this:

```javascript
const createProjectPackageJson = (tree, { appRoot }, copyFromFolder) => {
    // This needs to be copied and dependencies + devDependencies removed
    const sourcePackageJson = (0, devkit_1.readJsonFile)(path_1.default.posix.join(copyFromFolder, 'package.json'));
    const azureFunctionsVersion = sourcePackageJson.dependencies['@azure/functions'];
    sourcePackageJson.dependencies = { ['@azure/functions']: azureFunctionsVersion };
    sourcePackageJson.devDependencies = {};
    sourcePackageJson.main = `dist/${appRoot}/src/functions/*.js`;
    tree.write(path_1.default.posix.join(appRoot, 'package.json'), JSON.stringify(sourcePackageJson, null, 2));
};
```

After some debugging I realized that `@azure/functions` didn't exist in the created `package.json` file's `dependencies` section:

```shell
{
  "name": "",
  "version": "",
  "scripts": {
    "build": "tsc",
    "build:production": "npm run prestart && npm prune --production",
    "watch": "tsc --w",
    "prestart": "npm run build && func extensions install",
    "start:host": "func start",
    "start": "npm-run-all --parallel start:host watch",
    "test": "echo \"No tests yet...\""
  },
  "description": "",
  "devDependencies": {
    "@azure/functions": "^1.0.1-beta1",
    "npm-run-all": "^4.1.5",
    "typescript": "^3.3.3"
  }
}
```

I updated the source generator code to point to `devDependencies` instead and the generator ran without error.

I tried the generator (without my modifications) with `@azure/functions` in both `devDependencies`
and `dependencies` sections of the root `package.json`, each attempt resulted in the same error. 

# Additional Data

package.json:

```json
{
  "name": "azure-test",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {},
  "private": true,
  "engines": {
    "node": "20.9.0"
  },
  "dependencies": {
    "@azure/identity": "^4.0.0",
    "@nestjs/axios": "3.0.1",
    "@nestjs/common": "^10.2.10",
    "@nestjs/config": "3.1.1",
    "@nestjs/core": "10.2.10",
    "@nestjs/platform-express": "^10.2.10",
    "@nestjs/terminus": "^10.2.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1",
    "tslib": "^2.6.2",
    "xml-js": "^1.6.11",
    "tsconfig-paths": "^4.2.0"
  },
  "devDependencies": {
    "@nestjs/schematics": "^10.0.3",
    "@nestjs/testing": "^10.2.10",
    "@nx/eslint": "17.1.3",
    "@nx/eslint-plugin": "17.1.3",
    "@nx/jest": "17.1.3",
    "@nx/js": "17.1.3",
    "@nx/nest": "17.1.3",
    "@nx/node": "17.1.3",
    "@nx/webpack": "17.1.3",
    "@nx/workspace": "17.1.3",
    "@nxazure/func": "^1.1.0",
    "@swc-node/register": "~1.6.8",
    "@swc/core": "~1.3.100",
    "@types/jest": "^29.5.10",
    "@types/node": "~20.10.3",
    "@typescript-eslint/eslint-plugin": "^6.13.2",
    "@typescript-eslint/parser": "^6.13.2",
    "eslint": "~8.46.0",
    "eslint-config-prettier": "^9.0.0",
    "jest": "^29.7.0",
    "jest-environment-node": "^29.7.0",
    "nx": "17.1.3",
    "prettier": "^3.1.0",
    "ts-jest": "^29.1.1",
    "ts-node": "^10.9.1",
    "typescript": "^5.3.2",
    "npm-run-all": "^4.1.5"
    "@azure/functions": "^4.1.0",
  }
}
```

NPM info:

```shell
{
  npm: "10.1.0",
  node: "20.9.0",
}
```

**Comment by AlexPshul** [comment]
Hi @wgd3 ,
I recently updated the package to work only with V4 functions model.
Based on what you are describing, it looks like you might be using an older version of the [azure functions core tools](https://learn.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=windows%2Cisolated-process%2Cnode-v4%2Cpython-v2%2Chttp-trigger%2Ccontainer-apps&pivots=programming-language-typescript#install-the-azure-functions-core-tools).
You can check the version you are running by running the command `func --version`.
If I recall correctly, anything above **4.0.5390** should be fine.

Could you please check your version and/or install the latest version of the tools and try again?
Let me know how it goes.

**Comment by wgd3** [comment]
Thanks @AlexPshul! Here's the version:

```shell
> func --version
4.0.5455
```

**Comment by AlexPshul** [comment]
Hi again @wgd3,
I'm not sure why this happens on your end, but it looks like something might be misconfigured on your end.
Could you do another test, please?
What happens when you create a simple Azure Functions NodeJS project? Does it create a V3 or a V4 function?
You can run the `func init` command right in your project to create it using the same environment.

My suspicion is that something is making the generator to create the old V3 function, in which case that error would make sense, since the V3 functions didn't have the `@auzre/functions` package in the `dependencies` section, but in the `devDependencies` section.

Please let me know what you find. This sort of edge-cases can help me make the package better for everyone. :)

**Comment by AlexPshul** [comment]
I just noticed something that might cause this issue in some repos.
Make sure that if your `package.json` includes a reference to `azure-functions-core-tools`, it is up-to-date with the latest version.
If not, the issue above could happen.

With that said, I'm closing the issue for now.
Please let me know if this is still a problem.
