### ISSUE TITLE
Mono repo dist folder

### ISSUE THREAD

**Issue by fgoulet** [AlexPshul/nxazure#34]
Hello,

I have noticed that the build executor output js files to a dist folder at the same level of the project.

The others apps in my mono repo output the build into a common dist folder at the root.

I tried to add an output option to the build executor and make it identical to the others apps but it had no effect to the ouput to the dist folder.

   "build": {
      "executor": "@nxazure/func:build",
      "outputs": [
        "{options.outputPath}"
      ],
      "options": {
        "outputPath": "dist/apps/purview-harvester"
      }
    },

Just wondering if there is a reason for that.

Thank you

**Comment by AlexPshul** [comment]
Hi @fgoulet,
This is a limitation which is imposed by the functions themselves.
The runnables **must** be in the actual directory of the package.json and they must be ran from there.
This goes for both - running the functions locally and publishing it to Azure.

If I may ask, what issue are you trying to solve by moving all the output files to the main `dist` folder?

**Comment by fgoulet** [comment]
Hi Alex,
Thanks for the clarification. I have no issue in particular with that limitation. I'm new to nx and wanted to understand a little better how the different plugins may work together.
Thanks to your plugin, I was able to create an azure functions app in my nx monorepo and reference a plain typescript library project. So, it works great for me so far.

Thank you

**Comment by AlexPshul** [comment]
I'm glad it helped you. :)
NX is an amazing tool with many features to explore.
I'm closing the issue for now but feel free to open it again if you need to or if you find other problems.
