### ISSUE TITLE
Planned support of nx v20

### ISSUE THREAD

**Issue by Katli95** [AlexPshul/nxazure#36]
Just wanted to check if work was already in progress on the update? Or if you had an idea of how much work it would be? Might be open to PR myself if you believe a new package could be published before the middle of next week.

**Comment by AlexPshul** [comment]
I am definitely planning to support NX 20. It looks like a great leap forward.
However, it might take time from my end and I don't want to make any date promises, since there are many changes in that version.

I'll update in this thread once I release support for NX 20.

**Comment by AlexPshul** [comment]
@Katli95 
Migrated the package to NX 20 in v1.2.1.
If you experience any problems, feel free to reopen the issue.
