### ISSUE TITLE
use provided package manager to create build instead of hardcoded `npm i`

### ISSUE THREAD

**Issue by aamir-mns** [AlexPshul/nxazure#38]
[Here](https://github.com/AlexPshul/nxazure/blob/c8b1cf873938764bd3d0089cbed6f6cd68bf44fb/packages/func/src/executors/publish/executor.ts#L15) npm is used but we should be able to use pnpm or yarn and that should be configurable. Otherwise the result build might be different from what we use and test locally with pnpm or yarn.

**Comment by AlexPshul** [comment]
Thanks @aamir-mns !
That's a valid point.

I'll reply here once I release a version with this change.

**Comment by aamir-mns** [comment]
Thanks ❤️

**Comment by AlexPshul** [comment]
Starting from version 1.2.1, the workspace package manager will be used when installing function app dependencies before publishing it.
Let me know if it works for you.

**Comment by aamir-mns** [comment]
Thanks, I will check this soon

**Comment by AlexPshul** [comment]
Thanks @aamir-mns.

Please note,
The new package version (1.2.1) requires NX 20.

**Comment by aamir-mns** [comment]
It seems to be working as expected. Thanks ;)
