### ISSUE TITLE
Feature Request: Load Testing Setup with Grafana

### ISSUE THREAD

**Issue by AndrewRedican** [AlexPshul/nxazure#6]
I recently saw there is a new Azure Typescript function. Congratulations!
I was going to write my own, but I will use this insteas.

Could we include load testing?
For example, check this out: https://alex-klaus.com/load-test-k6-typescript-azure/

**Comment by AlexPshul** [comment]
Thanks @AndrewRedican !

I'm not sure what you mean by including this. The package is simply a tool to run Azure Functions in an NX workspace. If you want to implement with them load testing, you can do so just like with any other Azure Functions setup.
Am I missing something?

**Comment by AlexPshul** [comment]
I'm closing this for now due to inactivity of the thread.

**Comment by AlexPshul** [comment]
I'm closing this for now due to inactivity of the thread.
