### ISSUE TITLE
Type issues when attempting to use graphql in an nxazure project.

### ISSUE THREAD

**Issue by Falven** [AlexPshul/nxazure#8]
I am trying to use the [Apollo Server Integrations for Azure Functions](https://github.com/apollo-server-integrations/apollo-server-integration-azure-functions). These work fine in a regular Azure Functions project if you follow the instructions and additionally add `"esModuleInterop": true` to your `tsconfig`.

However in an `@nxazure/func` project, when attempting to build the function I get a bunch of type definition errors:

```shell
> nx run api:build

Compiling TypeScript files for project "api"...
node_modules/.pnpm/@apollo+cache-control-types@1.0.2_graphql@16.6.0/node_modules/@apollo/cache-control-types/dist/index.d.ts:1:15 - error TS2614: Module '"graphql"' has no exported member 'GraphQLCompositeType'. Did you mean to use 'import GraphQLCompositeType from "graphql"' instead?

1 import type { GraphQLCompositeType, GraphQLResolveInfo } from "graphql";
                ~~~~~~~~~~~~~~~~~~~~
node_modules/.pnpm/@apollo+cache-control-types@1.0.2_graphql@16.6.0/node_modules/@apollo/cache-control-types/dist/index.d.ts:1:37 - error TS2614: Module '"graphql"' has no exported member 'GraphQLResolveInfo'. Did you mean to use 'import GraphQLResolveInfo from "graphql"' instead?

1 import type { GraphQLCompositeType, GraphQLResolveInfo } from "graphql";
                                      ~~~~~~~~~~~~~~~~~~
node_modules/.pnpm/@apollo+server-gateway-interface@1.1.0_graphql@16.6.0/node_modules/@apollo/server-gateway-interface/dist/index.d.ts:2:15 - error TS2614: Module '"graphql"' has no exported member 'DocumentNode'. Did you mean to use 'import DocumentNode from "graphql"' instead?

...
```

I can provide the full list of errors (963 lines) if needed.

**Comment by Falven** [comment]
I) think I've figured it out - this issue is happening because the generator is appending `"baseUrl": "."` to the tsconfig. I thing it should only have `"rootDir": "."`.

**Comment by Falven** [comment]
Worked for me after this change. Putting out a PR.

**Comment by AlexPshul** [comment]
PR merged.
Thank you for taking the time to do this. ❤️
